/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import login.Login;

/**
 *
 * @author ASUS
 */
public class menu_admin extends javax.swing.JFrame {

    public Statement st;
    public ResultSet rs;
     Connection cn = koneksi.KoneksiDatabase.openConnection();

    private void cls() {

        idS.setText("");
        nama.setText("");
        harga.setText("");
        merk.setText("");
        stok.setText("");
        cmbJenis.setSelectedIndex(0);
        btnedit.setEnabled(false);
        btntambah.setEnabled(true);

    }

private boolean containsOnlyAlphanumeric(String text) {
            return text.matches("[a-zA-Z0-9]+");
        }
private boolean containsOnlyLettersAndSpace(String text) {
            return text.matches("[a-zA-Z ]*");
        }

private boolean containsOnlyLetters(String text) {
            return text.matches("[a-zA-Z]+");
        }

    private void Tampil() {
        try {
            st = cn.createStatement();
rs = st.executeQuery("SELECT * FROM skincare ORDER BY id");

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("Merk");
            model.addColumn("Product Name");
            model.addColumn("Stock");
            model.addColumn("Price");
            model.addColumn("Face Category");
//            int no = 1;
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            while (rs.next()) {
                Object[] data = {rs.getString("id"), rs.getString("merk"), rs.getString("nama"), rs.getString("stok"), rs.getString("price"), rs.getString("kategori")};
                model.addRow(data);
                tblData.setModel(model);
//                no++;
            }
//        ------------------
        } catch (Exception e) {
        }
    }

    /**
     * Creates new form menu_admin
     */
    public menu_admin() {
        initComponents();
        Tampil();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        merk = new javax.swing.JTextField();
        idS = new javax.swing.JTextField();
        stok = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        cmbJenis = new javax.swing.JComboBox<>();
        btntambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnedit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 224, 226));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblData.setForeground(new java.awt.Color(204, 67, 115));
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Code", "Merk", "Product Name", "Stock", "Price", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.setName("tblData"); // NOI18N
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 345, 756, 352));

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(165, 51, 86));
        jLabel5.setText("ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(165, 51, 86));
        jLabel4.setText("Merk Skincare");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 167, -1, -1));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(165, 51, 86));
        jLabel1.setText("Product Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 192, 646, -1));
        jPanel1.add(merk, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 164, 646, -1));

        idS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idSActionPerformed(evt);
            }
        });
        jPanel1.add(idS, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 136, 646, -1));
        jPanel1.add(stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 220, 646, -1));
        jPanel1.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 248, 646, -1));

        cmbJenis.setBackground(new java.awt.Color(204, 67, 115));
        cmbJenis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbJenis.setForeground(new java.awt.Color(255, 255, 255));
        cmbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oily", "Normal" }));
        cmbJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJenisActionPerformed(evt);
            }
        });
        jPanel1.add(cmbJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 115, -1));

        btntambah.setBackground(new java.awt.Color(204, 67, 115));
        btntambah.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        btntambah.setForeground(new java.awt.Color(255, 255, 255));
        btntambah.setText("Add");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        jPanel1.add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        btnHapus.setBackground(new java.awt.Color(204, 67, 115));
        btnHapus.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Delete");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 310, -1, -1));

        btnBatal.setBackground(new java.awt.Color(204, 67, 115));
        btnBatal.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Cancel");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 310, -1, -1));

        btnBack.setBackground(new java.awt.Color(204, 67, 115));
        btnBack.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(165, 51, 86));
        jLabel6.setText("Face Category");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 279, -1, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(165, 51, 86));
        jLabel3.setText("Price");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(165, 51, 86));
        jLabel7.setText("Stock");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logoimk__2_-removebg-preview (2).png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 0, 190, 100));

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(212, 77, 116));
        jLabel9.setText("s t o r e");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 80, -1, 50));

        btnedit.setBackground(new java.awt.Color(204, 67, 115));
        btnedit.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel1.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 710));

        jButton1.setBackground(new java.awt.Color(250, 224, 226));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(165, 51, 86));
        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        cls();
        idS.setEditable(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    private void cmbJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJenisActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_cmbJenisActionPerformed
private boolean containsDigit(String text) {
            for (char c : text.toCharArray()) {
                if (Character.isDigit(c)) {
                    return true;
                }
            }
            return false;
        }

    private boolean validasiInput() {
        try {
            // Validasi harga, harus berupa angka
            Integer.parseInt(harga.getText());

        } catch (NumberFormatException e) {
            // Jika ada pengecualian, tampilkan notifikasi
            JOptionPane.showMessageDialog(this, "Price Must Number", "INVALID", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    private boolean validasiInput1() {
        try {
            // Validasi stok, harus berupa angka
            Integer.parseInt(stok.getText());

        } catch (NumberFormatException e) {
            // Jika ada pengecualian, tampilkan notifikasi
            JOptionPane.showMessageDialog(this, "Stock Must Number", "INVALID", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    private boolean validasiInput2() {
        try {
            // Validasi stok, harus berupa angka
            Integer.parseInt(idS.getText());

        } catch (NumberFormatException e) {
            // Jika ada pengecualian, tampilkan notifikasi
            JOptionPane.showMessageDialog(this, "id Must Number", "INVALID", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        //        ITUNG DARI KIRI PKE INDEX , NO =1,NIK = 2 DST

    idS.setText(tblData.getValueAt(tblData.getSelectedRow(), 0).toString());
    merk.setText(tblData.getValueAt(tblData.getSelectedRow(), 1).toString());
    nama.setText(tblData.getValueAt(tblData.getSelectedRow(), 2).toString());
    stok.setText(tblData.getValueAt(tblData.getSelectedRow(), 3).toString());
    harga.setText(tblData.getValueAt(tblData.getSelectedRow(), 4).toString());
    cmbJenis.setSelectedItem(tblData.getValueAt(tblData.getSelectedRow(), 5).toString());
    idS.setEditable(false);
    btntambah.setEnabled(false);
    btnedit.setEnabled(true);
    }//GEN-LAST:event_tblDataMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if (idS.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Select the data you want to delete");
        } else {
            int jawab = JOptionPane.showConfirmDialog(null, "This data will be deleted, continue?", "Confirm", JOptionPane.YES_NO_OPTION);
            if (jawab == 0) {
                try {
                    st = cn.createStatement();
                    String sql = "DELETE FROM skincare WHERE id = '" + idS.getText() + "' ";
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data successfully deleted");
                    Tampil();
                    cls();
                    idS.setEditable(true);
                } catch (Exception e) {
                }
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void idSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idSActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
         if (isFormValid()) {
        try {
            st = cn.createStatement();
            String update = "UPDATE skincare SET merk = '" + merk.getText() + "', nama = '" + nama.getText() + "', stok = '" + stok.getText() + "', price = '" + harga.getText() + "', kategori = '" + cmbJenis.getSelectedItem().toString() + "' WHERE id = '" + idS.getText() + "'";
            st.executeUpdate(update);
            JOptionPane.showMessageDialog(null, "Data successfully changed");
            btntambah.setEnabled(true);
            btnedit.setEnabled(false);
            idS.setEditable(true);
            cls();
            Tampil();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_btneditActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        if (isFormValid()) {
            try {
                st = cn.createStatement();
                String cek = "SELECT * FROM skincare WHERE id = '" + idS.getText() + "'";
                rs = st.executeQuery(cek);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Data already exist");
                } else {
                    String sql = "INSERT INTO skincare VALUES ('" + idS.getText() + "','" + merk.getText() + "','" + nama.getText() + "','" + stok.getText() + "','" + harga.getText() + "','" + cmbJenis.getSelectedItem().toString() + "')";
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data added successfully");
                    cls();
                    Tampil();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btntambahActionPerformed
// Form validation method
private boolean isFormValid() {
    if (idS.getText().equals("") || nama.getText().equals("") || harga.getText().equals("") || merk.getText().equals("") || stok.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Data empty!!!", "Data Validation", JOptionPane.INFORMATION_MESSAGE);
        return false;
    }
    if (!validasiInput() || !validasiInput1() || !validasiInput2()) {
        return false;
    }
    if (!containsOnlyLettersAndSpace(nama.getText())) {
        JOptionPane.showMessageDialog(null, "Product Name only letters!");
        return false;
    }
    if (!containsOnlyLettersAndSpace(merk.getText())) {
        JOptionPane.showMessageDialog(null, "Merk only letters!");
        return false;
    }
    if (Integer.parseInt(harga.getText()) < 10000) {
        JOptionPane.showMessageDialog(null, "Minimum price 10000");
        return false;
    }
    if (Integer.parseInt(idS.getText()) < 1) {
        JOptionPane.showMessageDialog(null, "id > 0");
        return false;
    }
    if (Integer.parseInt(stok.getText()) < 1) {
        JOptionPane.showMessageDialog(null, "Minimum stock 1");
        return false;
    }
    return true;
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btntambah;
    private javax.swing.JComboBox<String> cmbJenis;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField idS;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField merk;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField stok;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables
}
